### ISSUE TITLE
[SERIOUSLY] Judgment line abnormal

### ISSUE THREAD

**Issue by Teages** [XionUzuki/PCtyx#3] opened 2020-03-07 12:42 UTC
Judgment line abnormal.Exception shift when play.

My English is not good.But videos can tell you where is the bug.

[Download here](https://mega.nz/#F!skMhAQIB!E1A6iCIm9e64BN2pdwcBxw)

**Comment by XionUzuki** [comment] 2020-03-07 15:52
Not a bug. Read Sync settings on top-left; After edit a page, scanlines and notes after where you edited which re-snc themselves. If you set it to Time, scanlines will go-way off.

The proper usage is edit the first page, turn sync to "Time" and "Delete all scanlines" (Toggle reminder if you forget), then re-do all the other scanlines in ascending order.

**Comment by XionUzuki** [comment] 2020-03-07 17:28
Fixed and will be deployed as a next bugfix.

This is due to older versions reads then try to sync with time, causing the scanline progressively shift. I changed it to sync with Y-position which the notes (other than Hold/Long note bars which may be slightly different)

This fix is also related to C2 export.

Thank you for bringing this into my attention.

**Comment by XionUzuki** [comment] 2020-03-09 17:01
issue resolved in v200.1 hotfix

**Closed as completed** 2020-03-09 17:00 UTC
Labels: bug
